INSERT INTO asset_label (asset_id, label, language, value) VALUES (6706, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6706, 'industry', 'en', 'Banks - Regional');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6706, 'sector', 'ru', 'Финансы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6706, 'industry', 'ru', 'Региональные банки');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6707, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6707, 'industry', 'en', 'Oil & Gas Integrated');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6707, 'sector', 'ru', 'Энергетика');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6707, 'industry', 'ru', 'Интегрированные нефтяные и газовые компании');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6708, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6708, 'industry', 'en', 'Banks - Regional');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6708, 'sector', 'ru', 'Финансы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6708, 'industry', 'ru', 'Региональные банки');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6709, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6709, 'industry', 'en', 'Oil & Gas Integrated');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6709, 'sector', 'ru', 'Энергетика');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6709, 'industry', 'ru', 'Интегрированные нефтяные и газовые компании');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6710, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6710, 'industry', 'en', 'Financial Data & Stock Exchanges');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6710, 'sector', 'ru', 'Финансы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6710, 'industry', 'ru', 'Финансовые биржи и финансовые данные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6711, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6711, 'industry', 'en', 'Oil & Gas E&P');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6711, 'sector', 'ru', 'Энергетика');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6711, 'industry', 'ru', 'Интегрированные нефтяные и газовые компании');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6712, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6712, 'industry', 'en', 'Banks - Regional');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6712, 'sector', 'ru', 'Финансы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6712, 'industry', 'ru', 'Региональные банки');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6713, 'sector', 'en', 'Retail');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6713, 'industry', 'en', 'Consumer Retail');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6713, 'sector', 'ru', 'Потребительские товары массового спроса');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6713, 'industry', 'ru', 'Розничная торговля потребительскими товарами массового спроса');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6714, 'sector', 'en', 'IT');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6714, 'industry', 'en', 'IT Services & Infrastructure');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6714, 'sector', 'ru', 'Информационные технологии');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6714, 'industry', 'ru', 'Предоставление Интернет-услуг и инфраструктуры');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6715, 'sector', 'en', 'Retail Trade');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6715, 'industry', 'en', 'Internet Retail');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6715, 'sector', 'ru', 'Розничная торговля');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6715, 'industry', 'ru', 'Интернет-розничная торговля');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6716, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6716, 'industry', 'en', 'Airlines');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6716, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6716, 'industry', 'ru', 'Авиакомпании');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6717, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6717, 'industry', 'en', 'Other Industrial Metals & Mining');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6717, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6717, 'industry', 'ru', 'Другие промышленные металлы и горнодобывающая промышленность');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6718, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6718, 'industry', 'en', 'Rental & Leasing Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6718, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6718, 'industry', 'ru', 'Услуги аренды и лизинга');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6719, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6719, 'industry', 'en', 'Steel');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6719, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6719, 'industry', 'ru', 'Сталь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6720, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6720, 'industry', 'en', 'Steel');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6720, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6720, 'industry', 'ru', 'Сталь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6721, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6721, 'industry', 'en', 'Oil & Gas Integrated');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6721, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6721, 'industry', 'ru', 'Золото');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6722, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6722, 'industry', 'en', 'Gold');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6722, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6722, 'industry', 'ru', 'Золото');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6723, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6723, 'industry', 'en', 'Oil & Gas Integrated');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6723, 'sector', 'ru', 'Услуги связи');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6723, 'industry', 'ru', 'Телекоммуникационные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6724, 'sector', 'en', 'Retail');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6724, 'industry', 'en', 'Consumer Retail');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6724, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6724, 'industry', 'ru', 'Алюминий');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6725, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6725, 'industry', 'en', 'Financial Data & Stock Exchanges');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6725, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6725, 'industry', 'ru', 'Сталь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6726, 'sector', 'en', 'Real Estate');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6726, 'industry', 'en', 'Real Estate - Diversified');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6726, 'sector', 'ru', 'Услуги связи');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6726, 'industry', 'ru', 'Телекоммуникационные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6727, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6727, 'industry', 'en', 'Oil & Gas Midstream');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6727, 'sector', 'ru', 'Услуги связи');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6727, 'industry', 'ru', 'Телекоммуникационные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6728, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6728, 'industry', 'en', 'Steel');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6728, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6728, 'industry', 'ru', 'Сталь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6729, 'sector', 'en', 'Communication Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6729, 'industry', 'en', 'Telecom Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6729, 'sector', 'ru', 'Услуги связи');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6729, 'industry', 'ru', 'Телекоммуникационные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6730, 'sector', 'en', 'Real Estate');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6730, 'industry', 'en', 'Real Estate - Development');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6730, 'sector', 'ru', 'Защита прав потребителей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6730, 'industry', 'ru', 'Напитки - Винодельни и ликероводочные заводы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6731, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6731, 'industry', 'en', 'Aluminum');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6731, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6731, 'industry', 'ru', 'Алюминий');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6732, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6732, 'industry', 'en', 'Steel');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6732, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6732, 'industry', 'ru', 'Сталь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6733, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6733, 'industry', 'en', 'Oil & Gas Integrated');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6733, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6733, 'industry', 'ru', 'Алюминий');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6734, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6734, 'industry', 'en', 'Banks — Regional');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6734, 'sector', 'ru', 'Технология');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6734, 'industry', 'ru', 'Программное обеспечение - Инфраструктура');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6735, 'sector', 'en', 'Communication Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6735, 'industry', 'en', 'Telecom Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6735, 'sector', 'ru', 'Услуги связи');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6735, 'industry', 'ru', 'Телекоммуникационные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6736, 'sector', 'en', 'Communication Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6736, 'industry', 'en', 'Telecom Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6736, 'sector', 'ru', 'Услуги связи');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6736, 'industry', 'ru', 'Телекоммуникационные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6737, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6737, 'industry', 'en', 'Other Precious Metals & Mining');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6737, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6737, 'industry', 'ru', 'Другие драгоценные металлы и горнодобывающая промышленность');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6738, 'sector', 'en', 'Real Estate');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6738, 'industry', 'en', 'Real Estate Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6738, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6738, 'industry', 'ru', 'Сталь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6739, 'sector', 'en', 'Communication Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6739, 'industry', 'en', 'Internet Content & Information');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6739, 'sector', 'ru', 'Услуги связи');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6739, 'industry', 'ru', 'Интернет-контент и информация');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6740, 'sector', 'en', 'Consumer Defensive');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6740, 'industry', 'en', 'Beverages - Wineries & Distilleries');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6740, 'sector', 'ru', 'Защита прав потребителей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6740, 'industry', 'ru', 'Напитки - Винодельни и ликероводочные заводы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6741, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6741, 'industry', 'en', 'Maritime transport activities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6741, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6741, 'industry', 'ru', 'Коксующийся уголь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6742, 'sector', 'en', 'Consumer Cyclical');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6742, 'industry', 'en', 'Auto Manufacturers');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6742, 'sector', 'ru', 'Потребительский циклический');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6742, 'industry', 'ru', 'Производители автомобилей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6743, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6743, 'industry', 'en', 'Human Resource Management Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6743, 'sector', 'ru', 'Защита прав потребителей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6743, 'industry', 'ru', 'Фермерские продукты');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6744, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6744, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6744, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6744, 'industry', 'ru', 'Морские перевозки');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6745, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6745, 'industry', 'en', 'Insurance - Diversified');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6745, 'sector', 'ru', 'Потребительский циклический');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6745, 'industry', 'ru', 'Специализированная розничная торговля');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6746, 'sector', 'en', 'IT');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6746, 'industry', 'en', 'Software — Development');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6746, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6746, 'industry', 'ru', 'Другие промышленные металлы и горнодобывающая промышленность');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6747, 'sector', 'en', 'IT');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6747, 'industry', 'en', 'Software — Development');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6747, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6747, 'industry', 'ru', 'Грузоперевозки');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6748, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6748, 'industry', 'en', 'Oil & Gas Integrated');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6748, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6748, 'industry', 'ru', 'Сельскохозяйственная и тяжелая строительная техника');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6749, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6749, 'industry', 'en', 'Utilities - Independent Power Producers');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6749, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6749, 'industry', 'ru', 'Электрооборудование и детали');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6750, 'sector', 'en', 'Non-essential consumer goods');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6750, 'industry', 'en', 'Provision of specialized consumer services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6750, 'sector', 'ru', 'Защита прав потребителей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6750, 'industry', 'ru', 'Услуги образования и обучения');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6751, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6751, 'industry', 'en', 'Agricultural Inputs');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6751, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6751, 'industry', 'ru', 'Сельскохозяйственные ресурсы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6752, 'sector', 'en', 'Non-essential consumer goods');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6752, 'industry', 'en', 'Manufacturing of clothing, accessories and luxury goods');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6752, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6752, 'industry', 'ru', 'Сельскохозяйственные ресурсы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6753, 'sector', 'en', 'Healthcare');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6753, 'industry', 'en', 'Healthcare services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6753, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6753, 'industry', 'ru', 'Другие промышленные металлы и горнодобывающая промышленность');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6754, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6754, 'industry', 'en', 'Aluminum');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6754, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6754, 'industry', 'ru', 'Алюминий');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6755, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6755, 'industry', 'en', 'Banks - Regional');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6755, 'sector', 'ru', 'Защита прав потребителей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6755, 'industry', 'ru', 'Услуги образования и обучения');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6756, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6756, 'industry', 'en', 'Oil & Gas E&P');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6756, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6756, 'industry', 'ru', 'Сельскохозяйственная и тяжелая строительная техника');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6757, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6757, 'industry', 'en', 'Specialized financial services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6757, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6757, 'industry', 'ru', 'Химикаты');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6758, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6758, 'industry', 'en', 'Diversified financial services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6758, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6758, 'industry', 'ru', 'Другие промышленные металлы и горнодобывающая промышленность');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6759, 'sector', 'en', 'Technology');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6759, 'industry', 'en', 'Software - Infrastructure');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6759, 'sector', 'ru', 'Технология');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6759, 'industry', 'ru', 'Программное обеспечение - Инфраструктура');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6760, 'sector', 'en', 'Consumer goods');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6760, 'industry', 'en', 'Production of agricultural products and services in the agricultural sector');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6760, 'sector', 'ru', 'Защита прав потребителей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6760, 'industry', 'ru', 'Напитки - Винодельни и ликероводочные заводы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6761, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6761, 'industry', 'en', 'Integrated Freight & Logistics');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6761, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6761, 'industry', 'ru', 'Интегрированные грузоперевозки и логистика');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6762, 'sector', 'en', 'IT');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6762, 'industry', 'en', 'Internet Services — Infrastructure');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6762, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6762, 'industry', 'ru', 'Сталь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6763, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6763, 'industry', 'en', 'Oil & Gas Refeinery & Sale');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6763, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6763, 'industry', 'ru', 'Аэрокосмическая промышленность и оборона');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6764, 'sector', 'en', 'Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6764, 'industry', 'en', 'Gold mining');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6764, 'sector', 'ru', 'Услуги связи');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6764, 'industry', 'ru', 'Телекоммуникационные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6765, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6765, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6765, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6765, 'industry', 'ru', 'Химикаты');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6766, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6766, 'industry', 'en', 'Banks - Regional');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6766, 'sector', 'ru', 'Здравоохранение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6766, 'industry', 'ru', 'Биотехнология');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6767, 'sector', 'en', 'Healthcare');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6767, 'industry', 'en', 'Healthcare services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6767, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6767, 'industry', 'ru', 'Проектирование и строительство');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6768, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6768, 'industry', 'en', 'Aerospace & Defense');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6768, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6768, 'industry', 'ru', 'Аэрокосмическая промышленность и оборона');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6769, 'sector', 'en', 'Consumer Cyclical');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6769, 'industry', 'en', 'Packaging & Containers');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6769, 'sector', 'ru', 'Потребительский циклический');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6769, 'industry', 'ru', 'Упаковка и контейнеры');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6770, 'sector', 'en', 'Consumer goods');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6770, 'industry', 'en', 'Retail consumer goods');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6770, 'sector', 'ru', 'Технология');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6770, 'industry', 'ru', 'Электронные компоненты');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6771, 'sector', 'en', 'Consumer Cyclical');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6771, 'industry', 'en', 'Department Stores');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6771, 'sector', 'ru', 'Потребительский циклический');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6771, 'industry', 'ru', 'Универмаги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6772, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6772, 'industry', 'en', 'Aerospace & Defense');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6772, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6772, 'industry', 'ru', 'Аэрокосмическая промышленность и оборона');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6773, 'sector', 'en', 'Healthcare');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6773, 'industry', 'en', 'Life Sciences Tools and Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6773, 'sector', 'ru', 'Здравоохранение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6773, 'industry', 'ru', 'Производители лекарств – специализированные и дженерики');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6774, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6774, 'industry', 'en', 'Utilities - Renewable');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6774, 'sector', 'ru', 'Технология');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6774, 'industry', 'ru', 'Научно-технические приборы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6775, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6775, 'industry', 'en', 'Banks — Regional');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6775, 'sector', 'ru', 'Финансы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6775, 'industry', 'ru', 'Региональные банки');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6776, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6776, 'industry', 'en', 'Utilities - Independent Power Producers');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6776, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6776, 'industry', 'ru', 'Проектирование и строительство');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6777, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6777, 'industry', 'en', 'Steel');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6777, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6777, 'industry', 'ru', 'Сталь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6778, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6778, 'industry', 'en', 'Marine Shipping');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6778, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6778, 'industry', 'ru', 'Морские перевозки');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6779, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6779, 'industry', 'en', 'Railroads');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6779, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6779, 'industry', 'ru', 'Железные дороги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6780, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6780, 'industry', 'en', 'Coking Coal');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6780, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6780, 'industry', 'ru', 'Коксующийся уголь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6781, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6781, 'industry', 'en', 'Gold');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6781, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6781, 'industry', 'ru', 'Золото');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6782, 'sector', 'en', 'Non-essential consumer goods');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6782, 'industry', 'en', 'Other');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6782, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6782, 'industry', 'ru', 'Изготовление металлоконструкций');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6783, 'sector', 'en', 'IT');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6783, 'industry', 'en', 'Software Development');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6783, 'sector', 'ru', 'Информационные технологии');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6783, 'industry', 'ru', 'Разработка программного обеспечения');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6784, 'sector', 'en', 'Consumer Defensive');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6784, 'industry', 'en', 'Farm Products');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6784, 'sector', 'ru', 'Потребительские продкуты');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6784, 'industry', 'ru', 'Фермерские продукты');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6785, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6785, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6785, 'sector', 'ru', 'Потребительские продкуты');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6785, 'industry', 'ru', 'Продуктовые магазины');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6786, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6786, 'industry', 'en', 'Marine Shipping');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6786, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6786, 'industry', 'ru', 'Морские перевозки');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6787, 'sector', 'en', 'Consumer Cyclical');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6787, 'industry', 'en', 'Specialty Retail');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6787, 'sector', 'ru', 'Потребительский циклический');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6787, 'industry', 'ru', 'Специализированная розничная торговля');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6788, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6788, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6788, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6788, 'industry', 'ru', 'Золото');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6789, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6789, 'industry', 'en', 'Other Industrial Metals & Mining');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6789, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6789, 'industry', 'ru', 'Другие промышленные металлы и горнодобывающая промышленность');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6790, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6790, 'industry', 'en', 'Trucking');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6790, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6790, 'industry', 'ru', 'Грузоперевозки');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6791, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6791, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6791, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6791, 'industry', 'ru', 'Сталь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6792, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6792, 'industry', 'en', 'Farm & Heavy Construction Machinery');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6792, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6792, 'industry', 'ru', 'Сельскохозяйственная и тяжелая строительная техника');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6793, 'sector', 'en', 'Real Estate');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6793, 'industry', 'en', 'Real Estate - Development');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6793, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6793, 'industry', 'ru', 'Сталь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6794, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6794, 'industry', 'en', 'Electrical Equipment & Parts');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6794, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6794, 'industry', 'ru', 'Электрооборудование и детали');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6795, 'sector', 'en', 'Real Estate');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6795, 'industry', 'en', 'Real Estate - Development');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6795, 'sector', 'ru', 'Услуги связи');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6795, 'industry', 'ru', 'Телекоммуникационные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6796, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6796, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6796, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6796, 'industry', 'ru', 'Аэрокосмическая промышленность и оборона');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6797, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6797, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6797, 'sector', 'ru', 'Потребительский циклический');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6797, 'industry', 'ru', 'Коммунальные предприятия - Регулируемая электроэнергетика');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6798, 'sector', 'en', 'IT');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6798, 'industry', 'en', 'Software Development');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6798, 'sector', 'ru', 'Потребительский циклический');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6798, 'industry', 'ru', 'Производители автомобилей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6799, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6799, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6799, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6799, 'industry', 'ru', 'Сталь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6800, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6800, 'industry', 'en', 'Utilities - Independent Power Producers');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6800, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6800, 'industry', 'ru', 'Другие промышленные металлы и горнодобывающая промышленность');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6801, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6801, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6801, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6801, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6802, 'sector', 'en', 'Healthcare');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6802, 'industry', 'en', 'Biotechnology');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6802, 'sector', 'ru', 'Здравоохранение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6802, 'industry', 'ru', 'Биотехнологии');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6803, 'sector', 'en', 'Consumer Defensive');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6803, 'industry', 'en', 'Packaged Foods');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6803, 'sector', 'ru', 'Защита прав потребителей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6803, 'industry', 'ru', 'Упакованные продукты питания');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6804, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6804, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6804, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6804, 'industry', 'ru', 'Золото');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6805, 'sector', 'en', 'Healthcare');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6805, 'industry', 'en', 'Biotechnology');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6805, 'sector', 'ru', 'Здравоохранение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6805, 'industry', 'ru', 'Биотехнологии');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6806, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6806, 'industry', 'en', 'Agricultural Inputs');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6806, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6806, 'industry', 'ru', 'Сельскохозяйственные ресурсы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6807, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6807, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6807, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6807, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6808, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6808, 'industry', 'en', 'Consumer Lending');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6808, 'sector', 'ru', 'Финансы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6808, 'industry', 'ru', 'Потребительское кредитование');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6809, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6809, 'industry', 'en', 'Other Industrial Metals & Mining');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6809, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6809, 'industry', 'ru', 'Другие промышленные металлы и горнодобывающая промышленность');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6810, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6810, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6810, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6810, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6811, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6811, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6811, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6811, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6812, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6812, 'industry', 'en', 'Oil & Gas Integrated');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6812, 'sector', 'ru', 'Энергетика');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6812, 'industry', 'ru', 'Интегрированные нефтяные и газовые компании');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6813, 'sector', 'en', 'Non-essential consumer goods');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6813, 'industry', 'en', 'Provision of specialized consumer services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6813, 'sector', 'ru', 'Неосновные потребительские товары');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6813, 'industry', 'ru', 'Предоставление специализированных потребительских услуг');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6814, 'sector', 'en', 'Real Estate');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6814, 'industry', 'en', 'Construction of real estate objects');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6814, 'sector', 'ru', 'Недвижимость');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6814, 'industry', 'ru', 'Строительство объектов недвижимого имущества');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6815, 'sector', 'en', 'Communication Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6815, 'industry', 'en', 'Internet Content & Information');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6815, 'sector', 'ru', 'Услуги связи');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6815, 'industry', 'ru', 'Интернет-контент и информация');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6816, 'sector', 'en', 'Consumer Defensive');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6816, 'industry', 'en', 'Education & Training Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6816, 'sector', 'ru', 'Защита прав потребителей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6816, 'industry', 'ru', 'Услуги образования и обучения');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6817, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6817, 'industry', 'en', 'Farm & Heavy Construction Machinery');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6817, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6817, 'industry', 'ru', 'Сельскохозяйственная и тяжелая строительная техника');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6818, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6818, 'industry', 'en', 'Chemicals');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6818, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6818, 'industry', 'ru', 'Химикаты');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6819, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6819, 'industry', 'en', 'Consumer Lending');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6819, 'sector', 'ru', 'Финансы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6819, 'industry', 'ru', 'Потребительское кредитование');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6820, 'sector', 'en', 'Real Estate');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6820, 'industry', 'en', 'Construction of real estate objects');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6820, 'sector', 'ru', 'Недвижимость');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6820, 'industry', 'ru', 'Строительство объектов недвижимого имущества');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6821, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6821, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6821, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6821, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6822, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6822, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6822, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6822, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6823, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6823, 'industry', 'en', 'Other Industrial Metals & Mining');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6823, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6823, 'industry', 'ru', 'Другие промышленные металлы и горнодобывающая промышленность');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6824, 'sector', 'en', 'Public utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6824, 'industry', 'en', 'Various utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6824, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6824, 'industry', 'ru', 'Различные коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6825, 'sector', 'en', 'Healthcare');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6825, 'industry', 'en', 'Pharmaceutical Retailers');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6825, 'sector', 'ru', 'Здравоохранение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6825, 'industry', 'ru', 'Фармацевтические ритейлеры');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6826, 'sector', 'en', 'Healthcare');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6826, 'industry', 'en', 'Healthcare services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6826, 'sector', 'ru', 'Здравоохранение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6826, 'industry', 'ru', 'Деятельность учреждений здравоохранения');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6827, 'sector', 'en', 'Consumer Defensive');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6827, 'industry', 'en', 'Beverages - Wineries & Distilleries');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6827, 'sector', 'ru', 'Защита прав потребителей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6827, 'industry', 'ru', 'Напитки - Винодельни и ликероводочные заводы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6828, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6828, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6828, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6828, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6829, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6829, 'industry', 'en', 'Consumer Lending');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6829, 'sector', 'ru', 'Финансы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6829, 'industry', 'ru', 'Потребительское кредитование');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6830, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6830, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6830, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6830, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6831, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6831, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6831, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6831, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6832, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6832, 'industry', 'en', 'Steel');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6832, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6832, 'industry', 'ru', 'Сталь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6833, 'sector', 'en', 'Non-essential consumer goods');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6833, 'industry', 'en', 'Consumer electronics manufacturing');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6833, 'sector', 'ru', 'Неосновные потребительские товары');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6833, 'industry', 'ru', 'Производство бытовой электроники');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6834, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6834, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6834, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6834, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6835, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6835, 'industry', 'en', 'Aerospace & Defense');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6835, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6835, 'industry', 'ru', 'Аэрокосмическая промышленность и оборона');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6836, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6836, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6836, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6836, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6837, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6837, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6837, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6837, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6838, 'sector', 'en', 'Communication Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6838, 'industry', 'en', 'Telecom Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6838, 'sector', 'ru', 'Услуги связи');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6838, 'industry', 'ru', 'Телекоммуникационные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6839, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6839, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6839, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6839, 'industry', 'ru', 'Сталь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6840, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6840, 'industry', 'en', 'Utilities - Independent Power Producers');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6840, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6840, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6841, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6841, 'industry', 'en', 'Chemicals');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6841, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6841, 'industry', 'ru', 'Химикаты');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6842, 'sector', 'en', 'Healthcare');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6842, 'industry', 'en', 'Biotechnology');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6842, 'sector', 'ru', 'Здравоохранение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6842, 'industry', 'ru', 'Биотехнология');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6843, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6843, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6843, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6843, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6844, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6844, 'industry', 'en', 'Engineering & Construction');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6844, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6844, 'industry', 'ru', 'Проектирование и строительство');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6845, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6845, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6845, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6845, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6846, 'sector', 'en', 'Consumer Defensive');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6846, 'industry', 'en', 'Confectioners');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6846, 'sector', 'ru', 'Защита прав потребителей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6846, 'industry', 'ru', 'Кондитеры');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6847, 'sector', 'en', 'Communication Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6847, 'industry', 'en', 'Telecom Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6847, 'sector', 'ru', 'Услуги связи');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6847, 'industry', 'ru', 'Телекоммуникационные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6848, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6848, 'industry', 'en', 'Banks - Regional');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6848, 'sector', 'ru', 'Финансы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6848, 'industry', 'ru', 'Региональные банки');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6849, 'sector', 'en', 'Technology');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6849, 'industry', 'en', 'Electronic Components');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6849, 'sector', 'ru', 'Технология');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6849, 'industry', 'ru', 'Электронные компоненты');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6850, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6850, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6850, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6850, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6851, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6851, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6851, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6851, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6852, 'sector', 'en', 'Communication Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6852, 'industry', 'en', 'Telecom Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6852, 'sector', 'ru', 'Услуги связи');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6852, 'industry', 'ru', 'Телекоммуникационные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6853, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6853, 'industry', 'en', 'Capital Markets');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6853, 'sector', 'ru', 'Финансы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6853, 'industry', 'ru', 'Управление активами и деятельность депозитарных банков');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6854, 'sector', 'en', 'Consumer Cyclical');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6854, 'industry', 'en', 'Auto Manufacturers');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6854, 'sector', 'ru', 'Потребительский циклический');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6854, 'industry', 'ru', 'Производители автомобилей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6855, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6855, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6855, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6855, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6856, 'sector', 'en', 'Consumer goods');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6856, 'industry', 'en', 'Production of alcohol and wines');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6856, 'sector', 'ru', 'Потребительские товары массового спроса');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6856, 'industry', 'ru', 'Производство спирта и вин');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6857, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6857, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6857, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6857, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6858, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6858, 'industry', 'en', 'Aerospace & Defense');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6858, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6858, 'industry', 'ru', 'Аэрокосмическая промышленность и оборона');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6859, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6859, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6859, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6859, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6860, 'sector', 'en', 'Technology');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6860, 'industry', 'en', 'Scientific & Technical Instruments');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6860, 'sector', 'ru', 'Технология');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6860, 'industry', 'ru', 'Научно-технические приборы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6861, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6861, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6861, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6861, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6862, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6862, 'industry', 'en', 'Thermal Coal');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6862, 'sector', 'ru', 'Энергетика');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6862, 'industry', 'ru', 'Уголь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6863, 'sector', 'en', 'Healthcare');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6863, 'industry', 'en', 'Drug Manufacturers - Specialty & Generic');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6863, 'sector', 'ru', 'Здравоохранение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6863, 'industry', 'ru', 'Производители лекарств – специализированные и дженерики');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6864, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6864, 'industry', 'en', 'Engineering & Construction');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6864, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6864, 'industry', 'ru', 'Проектирование и строительство');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6865, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6865, 'industry', 'en', 'Oil & Gas Integrated');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6865, 'sector', 'ru', 'Энергетика');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6865, 'industry', 'ru', 'Интегрированные нефтяные и газовые компании');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6866, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6866, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6866, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6866, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6867, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6867, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6867, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6867, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6868, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6868, 'industry', 'en', 'Aerospace & Defense');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6868, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6868, 'industry', 'ru', 'Аэрокосмическая промышленность и оборона');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6869, 'sector', 'en', 'Non-essential consumer goods');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6869, 'industry', 'en', 'Car production');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6869, 'sector', 'ru', 'Неосновные потребительские товары');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6869, 'industry', 'ru', 'Производители автомобилей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6870, 'sector', 'en', 'Healthcare');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6870, 'industry', 'en', 'Medical Care Facilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6870, 'sector', 'ru', 'Здравоохранение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6870, 'industry', 'ru', 'Медицинские учреждения');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6871, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6871, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6871, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6871, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6872, 'sector', 'en', 'Consumer Cyclical');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6872, 'industry', 'en', 'Auto Manufacturers');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6872, 'sector', 'ru', 'Потребительский циклический');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6872, 'industry', 'ru', 'Производители автомобилей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6873, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6873, 'industry', 'en', 'Utilities - Independent Power Producers');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6873, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6873, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6874, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6874, 'industry', 'en', 'Oil & Gas E&P');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6874, 'sector', 'ru', 'Энергетика');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6874, 'industry', 'ru', 'Разведка и добыча нефти и газа');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6875, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6875, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6875, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6875, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6876, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6876, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6876, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6876, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6877, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6877, 'industry', 'en', 'Specialty Chemicals');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6877, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6877, 'industry', 'ru', 'Специальные химикаты');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6878, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6878, 'industry', 'en', 'Insurance - Diversified');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6878, 'sector', 'ru', 'Финансы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6878, 'industry', 'ru', 'Страхование');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6879, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6879, 'industry', 'en', 'Chemicals');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6879, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6879, 'industry', 'ru', 'Химикаты');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6880, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6880, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6880, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6880, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6881, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6881, 'industry', 'en', 'Storage and transportation of oil and gas');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6881, 'sector', 'ru', 'Энергетика');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6881, 'industry', 'ru', 'Хранение и транспортировка нефти и газа');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6882, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6882, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6882, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6882, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6883, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6883, 'industry', 'en', 'Metal Fabrication');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6883, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6883, 'industry', 'ru', 'Изготовление металлоконструкций');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6884, 'sector', 'en', 'Consumer Cyclical');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6884, 'industry', 'en', 'Auto Parts');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6884, 'sector', 'ru', 'Потребительский циклический');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6884, 'industry', 'ru', 'Автозапчасти');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6885, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6885, 'industry', 'en', 'Specialty Chemicals');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6885, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6885, 'industry', 'ru', 'Специальные химикаты');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6886, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6886, 'industry', 'en', 'Banks - Regional');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6886, 'sector', 'ru', 'Финансы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6886, 'industry', 'ru', 'Региональные банки');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6887, 'sector', 'en', 'Consumer Defensive');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6887, 'industry', 'en', 'Grocery Stores');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6887, 'sector', 'ru', 'Защита прав потребителей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6887, 'industry', 'ru', 'Продуктовые магазины');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6888, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6888, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6888, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6888, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6889, 'sector', 'en', 'Technology');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6889, 'industry', 'en', 'Electronic Components');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6889, 'sector', 'ru', 'Технология');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6889, 'industry', 'ru', 'Электронные компоненты');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6890, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6890, 'industry', 'en', 'Steel');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6890, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6890, 'industry', 'ru', 'Сталь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6891, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6891, 'industry', 'en', 'Asset Management');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6891, 'sector', 'ru', 'Финансы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6891, 'industry', 'ru', 'Управление активами');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6892, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6892, 'industry', 'en', 'Gold');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6892, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6892, 'industry', 'ru', 'Золото');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6893, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6893, 'industry', 'en', 'Oil & Gas E&P');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6893, 'sector', 'ru', 'Энергетика');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6893, 'industry', 'ru', 'Разведка и добыча нефти и газа');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6894, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6894, 'industry', 'en', 'Oil & Gas Refeinery & Sale');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6894, 'sector', 'ru', 'Энергетика');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6894, 'industry', 'ru', 'Переработка и сбыт нефти и газа');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6895, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6895, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6895, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6895, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6896, 'sector', 'en', 'Consumer Defensive');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6896, 'industry', 'en', 'Confectioners');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6896, 'sector', 'ru', 'Защита прав потребителей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6896, 'industry', 'ru', 'Кондитеры');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6897, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6897, 'industry', 'en', 'Banks - Regional');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6897, 'sector', 'ru', 'Финансы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6897, 'industry', 'ru', 'Региональные банки');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6898, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6898, 'industry', 'en', 'Oil & Gas Refeinery & Sale');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6898, 'sector', 'ru', 'Энергетика');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6898, 'industry', 'ru', 'Переработка и сбыт нефти и газа');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6899, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6899, 'industry', 'en', 'Airlines');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6899, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6899, 'industry', 'ru', 'Авиакомпании');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6900, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6900, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6900, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6900, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6901, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6901, 'industry', 'en', 'Steel');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6901, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6901, 'industry', 'ru', 'Сталь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6902, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6902, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6902, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6902, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6903, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6903, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6903, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6903, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6904, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6904, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6904, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6904, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6905, 'sector', 'en', 'Basic Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6905, 'industry', 'en', 'Steel');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6905, 'sector', 'ru', 'Основные материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6905, 'industry', 'ru', 'Сталь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6906, 'sector', 'en', 'Consumer Cyclical');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6906, 'industry', 'en', 'Restaurants');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6906, 'sector', 'ru', 'Потребительский циклический');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6906, 'industry', 'ru', 'Рестораны');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6907, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6907, 'industry', 'en', 'Banks - Regional');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6907, 'sector', 'ru', 'Финансы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6907, 'industry', 'ru', 'Региональные банки');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6908, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6908, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6908, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6908, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6909, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6909, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6909, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6909, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6910, 'sector', 'en', 'Financial Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6910, 'industry', 'en', 'Banks - Regional');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6910, 'sector', 'ru', 'Финансы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6910, 'industry', 'ru', 'Региональные банки');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6911, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6911, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6911, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6911, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6912, 'sector', 'en', 'Real Estate');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6912, 'industry', 'en', 'Real Estate Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6912, 'sector', 'ru', 'Недвижимость');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6912, 'industry', 'ru', 'Операционные компании на рынке недвижимости');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6913, 'sector', 'en', 'Communication Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6913, 'industry', 'en', 'Telecom Services');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6913, 'sector', 'ru', 'Услуги связи');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6913, 'industry', 'ru', 'Телекоммуникационные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6914, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6914, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6914, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6914, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6915, 'sector', 'en', 'Industrials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6915, 'industry', 'en', 'Aerospace & Defense');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6915, 'sector', 'ru', 'Промышленные');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6915, 'industry', 'ru', 'Аэрокосмическая промышленность и оборона');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6916, 'sector', 'en', 'Materials');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6916, 'industry', 'en', 'Production of paper and plastic packaging materials and goods');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6916, 'sector', 'ru', 'Материалы');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6916, 'industry', 'ru', 'Производство бумажных и пластиковых упаковочных материалов и товаров');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6917, 'sector', 'en', 'Utilities');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6917, 'industry', 'en', 'Utilities - Regulated Electric');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6917, 'sector', 'ru', 'Коммунальные услуги');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6917, 'industry', 'ru', 'Электроснабжение');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6918, 'sector', 'en', 'Consumer Cyclical');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6918, 'industry', 'en', 'Auto Parts');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6918, 'sector', 'ru', 'Потребительский циклический');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6918, 'industry', 'ru', 'Автозапчасти');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6919, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6919, 'industry', 'en', 'Thermal Coal');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6919, 'sector', 'ru', 'Энергетика');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6919, 'industry', 'ru', 'Уголь');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6920, 'sector', 'en', 'Consumer Cyclical');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6920, 'industry', 'en', 'Auto Manufacturers');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6920, 'sector', 'ru', 'Потребительский циклический');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6920, 'industry', 'ru', 'Производители автомобилей');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6921, 'sector', 'en', 'Real Estate');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6921, 'industry', 'en', 'Diversified real estate operations');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6921, 'sector', 'ru', 'Недвижимость');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6921, 'industry', 'ru', 'Диверсифицированные операции с недвижимостью');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6922, 'sector', 'en', 'Energy');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6922, 'industry', 'en', 'Oil & Gas E&P');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6922, 'sector', 'ru', 'Энергетика');
INSERT INTO asset_label (asset_id, label, language, value) VALUES (6922, 'industry', 'ru', 'Разведка и добыча нефти и газа');
